


option('build_mode', type: 'combo', choices: ['debug', 'release'], value: 'debug', description: 'build mode defines the bulding state out of (debug, release)')
option('rend_api', type: 'combo', choices: ['opengl'], value: 'opengl', description: 'build mode defines the rendering api (opengl)')
option('platform', type: 'combo', choices: ['linux', 'windows', 'android'], value: 'linux', description: 'build mode defines the platform the the app will work on')


